services:
  db:
    image: postgres:15
    container_name: pg-container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: PasswordDb
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: password-generator-container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=PasswordDb;Username=admin;Password=admin